// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-1:ccefdb22-7a0e-44ae-87f7-53bd8255713f',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_mobile_analytics_app_id': 'bd6c14806bf34ed6898f49bcbd595af0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3897cf27-6d38-4311-83f6-445ee4fbb4ef',
    'aws_project_name': 'iot-mobile',
    'aws_project_region': 'ap-northeast-1',
    'aws_resource_name_prefix': 'iotmobile-mobilehub-1316078810',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'iotmobile-userfiles-mobilehub-1316078810',
    'aws_user_files_s3_bucket_region': 'ap-northeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-1_2KoxZ8JxR',
    'aws_user_pools_web_client_id': '7frpvcbd2r421nbp4j9gfa7s3j',
    'aws_appsync_graphqlEndpoint': 'https://5xekhmidyjcnxgces66rtaah7u.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    'aws_appsync_region': 'ap-northeast-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
    'aws_appsync_apiKey': 'da2-4zqmgkhvz5b73ajuatcqfpcnfi',
}

export default awsmobile;
