// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-1:c35eb22b-a765-4bb2-b1c2-1819b50e60ae',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_mobile_analytics_app_id': 'dd83c0ee882f442fa0fa76ce87eef9ed',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '19a59739-d876-47e7-a60a-1e9baa516a92',
    'aws_project_name': 'iot',
    'aws_project_region': 'ap-northeast-1',
    'aws_resource_name_prefix': 'iot-mobilehub-124497977',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'iot-userfiles-mobilehub-124497977',
    'aws_user_files_s3_bucket_region': 'ap-northeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-1_DlXJc0xUN',
    'aws_user_pools_web_client_id': '3ltmpcpqoj1en5beiqqq7nqor8',
    'aws_appsync_graphqlEndpoint': 'https://r76uktcoofdxhplhflzcq7fjki.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    'aws_appsync_region': 'ap-northeast-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
