// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cognito_identity_pool_id': 'ap-northeast-1:d67970ff-8958-4536-9228-06a54223d90b',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_project_id': '0d421a8c-1ad1-4689-91d0-7a393bf98194',
    'aws_project_name': 'SmartHouse',
    'aws_project_region': 'ap-northeast-1',
    'aws_resource_name_prefix': 'smarthouse-mobilehub-467026891',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'smarthouse-userfiles-mobilehub-467026891',
    'aws_user_files_s3_bucket_region': 'ap-northeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-1_YLtRJHIsC',
    'aws_user_pools_web_client_id': '1ujo2dsrse7rgmvo0bvn207s0t',
    'aws_appsync_graphqlEndpoint': 'https://gm3opa3fqrh7pexiumbp65hirq.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    'aws_appsync_region': 'ap-northeast-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
